<?php

declare(strict_types=1);

namespace Heyosseus\Sloppy\Output;

use Heyosseus\Sloppy\Analysis\AnalysisResult;
use Heyosseus\Sloppy\Analysis\Finding;
use Heyosseus\Sloppy\Contracts\Formatter;
use Heyosseus\Sloppy\Integrations\Tooling\RectorRules;

/**
 * A Rector configuration that fixes what this run found.
 *
 * Deliberately narrow: only the rules that address findings actually present,
 * and only over the files they were found in. A generated config that pulled
 * in a prepared set would rewrite code nobody complained about, produce a diff
 * nobody asked to review, and teach the team that `--fix` is not safe to run.
 *
 * Findings with no automated fix are listed as comments at the top with the
 * reason, because the alternative -- silence -- reads as "Rector handled it".
 */
final readonly class RectorFormatter implements Formatter
{
    public function format(AnalysisResult $result): string
    {
        $ids = [];
        $paths = [];

        foreach ($result->findings as $finding) {
            $ids[$finding->ruleId] = ($ids[$finding->ruleId] ?? 0) + 1;

            if (RectorRules::fixes($finding->ruleId)) {
                $paths[$finding->location->relativePath] = true;
            }
        }

        ksort($ids);
        $rules = RectorRules::forAll(array_keys($ids));
        $files = array_keys($paths);
        sort($files);

        $lines = [
            '<?php',
            '',
            'declare(strict_types=1);',
            '',
            '// Generated by `sloppy --format=rector`. Run it with:',
            '//',
            '//     vendor/bin/rector process --config=rector-sloppy.php',
            '//',
            ...$this->notes($ids, $result),
            '',
            'use Rector\Config\RectorConfig;',
            '',
            'return RectorConfig::configure()',
        ];

        $lines[] = '    ->withPaths([';
        $lines = [...$lines, ...$this->entries($files, static fn (string $file): string => "__DIR__.'/".$file."'")];
        $lines[] = '    ])';
        $lines[] = '    ->withRules([';
        $lines = [...$lines, ...$this->entries($rules, static fn (string $class): string => '\\'.$class.'::class')];
        $lines[] = '    ]);';

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    /**
     * @param  list<string>  $values
     * @param  callable(string): string  $render
     * @return list<string>
     */
    private function entries(array $values, callable $render): array
    {
        return array_map(static fn (string $value): string => '        '.$render($value).',', $values);
    }

    /**
     * @param  array<string, int>  $ids
     * @return list<string>
     */
    private function notes(array $ids, AnalysisResult $result): array
    {
        $fixed = 0;
        $lines = [];

        foreach ($ids as $id => $count) {
            if (RectorRules::fixes($id)) {
                $fixed += $count;
            }
        }

        $lines[] = sprintf('// Fixes %d of %d finding(s) in this run.', $fixed, $result->count());

        foreach ($ids as $id => $count) {
            if (RectorRules::fixes($id)) {
                continue;
            }

            $reason = RectorRules::reason($id);

            $lines[] = sprintf(
                '// %s x%d: no automated fix%s.',
                $id,
                $count,
                $reason === null ? '' : ' -- '.$reason,
            );
        }

        return $lines;
    }

    /**
     * The findings this configuration will not touch, for a caller that wants
     * to say so in its own words rather than read the comments.
     *
     * @param  list<Finding>  $findings
     * @return list<Finding>
     */
    public static function unfixable(array $findings): array
    {
        return array_values(array_filter(
            $findings,
            static fn (Finding $finding): bool => ! RectorRules::fixes($finding->ruleId),
        ));
    }
}
