<?php

declare(strict_types=1);

namespace Heyosseus\Sloppy\Agent;

use Heyosseus\Sloppy\Analysis\RuleRegistry;
use Heyosseus\Sloppy\Analysis\Severity;
use Heyosseus\Sloppy\Configuration\Configuration;
use Heyosseus\Sloppy\Contracts\Rule;
use Heyosseus\Sloppy\Sloppy;

/**
 * The project's rules, written for whoever is generating the next file.
 *
 * Increasingly that is a model, and a model cannot read `config/sloppy.php`
 * before it writes -- but it does read `CLAUDE.md`, `.cursorrules` and
 * `AGENTS.md`, every time, before touching anything. Putting the rules there
 * moves the feedback from "the build failed" to "the code was never written
 * that way", which is the only place a linter's advice is free.
 *
 * The output describes the configured run, not the shipped defaults: a project
 * that turned three rules off, raised a threshold or has no Laravel gets a
 * file that says so, because a file listing rules that will not fire teaches
 * the reader to distrust the rest of it.
 */
final readonly class RulesetGenerator
{
    public function __construct(
        private RuleRegistry $registry,
        private Configuration $configuration,
        private string $version = Sloppy::VERSION,
    ) {}

    public static function for(Sloppy $sloppy): self
    {
        return new self($sloppy->rules(), $sloppy->configuration);
    }

    public function generate(RulesetFormat $format): string
    {
        return $format->isJson() ? $this->json($format) : $this->markdown($format);
    }

    private function markdown(RulesetFormat $format): string
    {
        $lines = [
            '# Sloppy: code rules for this repository',
            '',
            $format->preamble(),
            '',
            sprintf('Generated by Sloppy %s (`sloppy rules --format=%s`). Re-run it when the configuration changes.', $this->version, $format->value),
            '',
            '## Before you call a task finished',
            '',
            'Run the analyser over your own change and fix what it introduced:',
            '',
            '```bash',
            sprintf('vendor/bin/sloppy diff main --fail-on=%s', $this->threshold()),
            '```',
            '',
            'Inherited findings are not yours to fix in passing. New ones are.',
            '',
            '## This project',
            '',
            sprintf('- Analysed paths: %s', implode(', ', $this->configuration->paths())),
            sprintf('- Framework rules: %s', $this->configuration->framework()),
            sprintf('- Fails on: %s and above', $this->threshold()),
            sprintf('- Confidence floor: %d', $this->configuration->minConfidence()),
            '',
            sprintf('## The %d rules in force', $this->registry->count()),
            '',
        ];

        foreach ($this->registry->rules() as $rule) {
            $lines = [...$lines, ...$this->rule($rule)];
        }

        return implode(PHP_EOL, [...$lines, ...$this->skipped()]).PHP_EOL;
    }

    /**
     * @return list<string>
     */
    private function rule(Rule $rule): array
    {
        return [
            sprintf('### %s %s', $rule->id(), $rule->name()),
            '',
            sprintf('- Category: %s, severity: %s', $rule->category()->label(), $rule->severity()->value),
            sprintf('- Flags: %s', $rule->description()),
            sprintf('- Why it costs: %s', $rule->explanation()),
            sprintf('- Write it this way instead: %s', RuleGuidance::for($rule)),
            '',
        ];
    }

    /**
     * @return list<string>
     */
    private function skipped(): array
    {
        $skipped = $this->registry->skipped();

        if ($skipped === []) {
            return [];
        }

        return [
            '## Not in force here',
            '',
            sprintf(
                '%s do not apply to this project: they describe a framework it does not use. Do not write code to satisfy them.',
                implode(', ', $skipped),
            ),
            '',
        ];
    }

    private function json(RulesetFormat $format): string
    {
        $rules = [];

        foreach ($this->registry->rules() as $rule) {
            $rules[] = [
                'id' => $rule->id(),
                'name' => $rule->name(),
                'category' => $rule->category()->value,
                'severity' => $rule->severity()->value,
                'description' => $rule->description(),
                'explanation' => $rule->explanation(),
                'guidance' => RuleGuidance::for($rule),
            ];
        }

        $encoded = json_encode([
            'schema' => 1,
            'tool' => 'sloppy',
            'version' => $this->version,
            'purpose' => $format->preamble(),
            'project' => [
                'paths' => $this->configuration->paths(),
                'framework' => $this->configuration->framework(),
                'fail_on' => $this->threshold(),
                'min_confidence' => $this->configuration->minConfidence(),
            ],
            'rules' => $rules,
            'rules_not_in_force' => $this->registry->skipped(),
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        return ($encoded === false ? '{}' : $encoded)."\n";
    }

    private function threshold(): string
    {
        $severity = $this->configuration->failOn();

        return $severity instanceof Severity ? $severity->value : 'never';
    }
}
