<?php

declare(strict_types=1);

namespace Heyosseus\Sloppy\Scoring;

use Stringable;

/**
 * A slop score out of 100, where 100 means nothing was flagged.
 *
 * This is a code-quality risk measure. It is explicitly not a claim that some
 * percentage of the code was generated by a machine.
 */
final readonly class Score implements Stringable
{
    public function __construct(
        public int $value,
        public ScoreBand $band,
        public float $penalty,
        public float $density,
    ) {}

    public function label(): string
    {
        return $this->band->label();
    }

    public function __toString(): string
    {
        return $this->value.'/100';
    }

    /**
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
            'value' => $this->value,
            'band' => $this->band->value,
            'label' => $this->band->label(),
            'penalty' => round($this->penalty, 3),
            'penalty_density' => round($this->density, 3),
        ];
    }
}
