<?php

declare(strict_types=1);

namespace Heyosseus\Sloppy\Runner;

use Heyosseus\Sloppy\Analysis\AnalysisResult;
use Heyosseus\Sloppy\Analysis\Finding;
use Heyosseus\Sloppy\Fix\NarrativeCommentRemover;
use Heyosseus\Sloppy\Integrations\Tooling\ProcessToolRunner;
use Heyosseus\Sloppy\Integrations\Tooling\RectorRules;
use Heyosseus\Sloppy\Integrations\Tooling\ToolRunner;
use Heyosseus\Sloppy\Output\RectorFormatter;
use Heyosseus\Sloppy\Sloppy;
use Throwable;

/**
 * Hand the fixable findings to Rector, then hand the result to Pint.
 *
 * Sloppy does not rewrite code itself. Two tools in this ecosystem already do
 * it well, every Laravel project has at least one of them, and a third
 * rewriter with its own idea of formatting would fight both. What Sloppy knows
 * that they do not is *which* of their rules this project currently needs, so
 * that is what it contributes: a generated Rector config scoped to the files
 * that actually have findings, run, and then formatted back into the project's
 * own style by Pint.
 *
 * One rewrite Sloppy does make itself: comments SL109 found restating the
 * line below them are deleted, because no Rector rule knows which ones they
 * are and deleting them loses nothing the code does not already say.
 *
 * Findings with no automated fix are reported rather than passed over -- the
 * point of the command is to shorten the list, and knowing what is left is
 * half of that.
 */
final readonly class FixRunner
{
    /** The line every configuration RectorFormatter writes opens with. */
    private const string GENERATED_MARKER = '// Generated by `sloppy';

    public function __construct(private ToolRunner $tools = new ProcessToolRunner) {}

    public function run(Sloppy $sloppy, FixOptions $options, RunnerOutput $output): ExitCode
    {
        try {
            $sloppy = (new ConfigurationResolver)->resolve($sloppy, $options, $output);

            if (! $sloppy->configuration->enabled()) {
                $output->info('Sloppy is disabled (sloppy.enabled is false).');

                return ExitCode::Success;
            }

            $before = $sloppy->analyze();
        } catch (Throwable $exception) {
            $output->error($exception->getMessage());

            return ExitCode::Error;
        }

        return $this->fix($sloppy, $before, $options, $output);
    }

    private function fix(Sloppy $sloppy, AnalysisResult $before, FixOptions $options, RunnerOutput $output): ExitCode
    {
        if ($before->isEmpty()) {
            $output->info('Nothing to fix: no findings.');

            return ExitCode::Success;
        }

        $fixable = array_values(array_filter(
            $before->findings,
            static fn (Finding $finding): bool => RectorRules::fixes($finding->ruleId),
        ));

        $configPath = $sloppy->configuration->absolutePath($options->configFile);

        // Checked before anything is rewritten: a run that removed comments
        // and then refused to go on would leave half a fix behind.
        if ($fixable !== [] && is_file($configPath) && ! $this->generatedBySloppy($configPath)) {
            $output->error(sprintf(
                '%s already exists and was not generated by Sloppy, so it was left alone. Pass --rector-config=<another file> to write the configuration somewhere else.',
                $options->configFile,
            ));

            return ExitCode::Error;
        }

        $comments = $this->removeComments($sloppy, $before, $options, $output);

        if ($fixable === []) {
            $this->reportRemaining($this->without($before->findings, $comments), $output);

            if ($comments === []) {
                return ExitCode::Success;
            }

            $failures = (new FixToolchain($this->tools))->run($sloppy->configuration->basePath, $options->withoutRector(), [], $this->paths($comments), $output);
            $this->reportDelta($sloppy, $before, $options, $output);

            return $failures > 0 ? ExitCode::Error : ExitCode::Success;
        }

        if (@file_put_contents($configPath, (new RectorFormatter)->format($before)) === false) {
            $output->error(sprintf('Could not write the Rector configuration to %s.', $configPath));

            return ExitCode::Error;
        }

        $output->notice(sprintf(
            '%d of %d finding(s) have an automated fix. Wrote %s.',
            count($fixable),
            $before->count(),
            $options->configFile,
        ));

        $failures = (new FixToolchain($this->tools))->run($sloppy->configuration->basePath, $options, $this->paths($fixable), $this->paths($comments), $output);

        // --no-rector means "write the configuration and stop for review", so
        // the file it wrote is the point of the run and is never cleaned up.
        if (! $options->withRector) {
            $output->notice(sprintf('Rector was skipped; %s is left in place for review.', $options->configFile));
        } elseif (! $options->keepConfig && is_file($configPath)) {
            @unlink($configPath);
        }

        $this->reportRemaining($this->without(RectorFormatter::unfixable($before->findings), $comments), $output);
        $this->reportDelta($sloppy, $before, $options, $output);

        return $failures > 0 ? ExitCode::Error : ExitCode::Success;
    }

    /**
     * Whether the file at this path is one Sloppy wrote, and so one it may
     * overwrite and delete. Anything else is the user's.
     */
    private function generatedBySloppy(string $path): bool
    {
        $head = @file_get_contents($path, length: 512);

        return is_string($head) && str_contains($head, self::GENERATED_MARKER);
    }

    /**
     * Delete the comments that only restate their code, before Rector runs,
     * so Pint formats both rewrites in one pass.
     *
     * @return list<Finding> The findings whose comment went.
     */
    private function removeComments(Sloppy $sloppy, AnalysisResult $before, FixOptions $options, RunnerOutput $output): array
    {
        if (! $options->withComments) {
            return [];
        }

        $removed = (new NarrativeCommentRemover)->remove($sloppy->configuration->basePath, $before->findings, $options->dryRun);

        if ($removed !== []) {
            $output->notice(sprintf(
                '%s %d comment(s) that only restated their code, in %d file(s).',
                $options->dryRun ? 'Would remove' : 'Removed',
                count($removed),
                count($this->paths($removed)),
            ));
        }

        return $removed;
    }

    /**
     * @param  list<Finding>  $findings
     * @param  list<Finding>  $handled
     * @return list<Finding>
     */
    private function without(array $findings, array $handled): array
    {
        return array_values(array_filter(
            $findings,
            static fn (Finding $finding): bool => ! in_array($finding, $handled, true),
        ));
    }

    /**
     * @param  list<Finding>  $findings
     * @return list<string>
     */
    private function paths(array $findings): array
    {
        $paths = [];

        foreach ($findings as $finding) {
            $paths[$finding->location->relativePath] = true;
        }

        $unique = array_keys($paths);
        sort($unique);

        return $unique;
    }

    /**
     * @param  list<Finding>  $remaining
     */
    private function reportRemaining(array $remaining, RunnerOutput $output): void
    {
        if ($remaining === []) {
            return;
        }

        $counts = [];

        foreach ($remaining as $finding) {
            $counts[$finding->ruleId] = ($counts[$finding->ruleId] ?? 0) + 1;
        }

        ksort($counts);

        $output->warn(sprintf(
            '%d finding(s) need a person: %s.',
            count($remaining),
            implode(', ', array_map(
                static fn (string $id, int $count): string => sprintf('%s x%d', $id, $count),
                array_keys($counts),
                array_values($counts),
            )),
        ));
    }

    private function reportDelta(Sloppy $sloppy, AnalysisResult $before, FixOptions $options, RunnerOutput $output): void
    {
        if ($options->dryRun) {
            $output->info('Dry run: no source file was changed; only the Rector configuration was written.');

            return;
        }

        // Not guarded: this is the second run of an analysis that already
        // succeeded with the same configuration, and the command surfaces
        // handle anything a rewriter could have broken.
        $after = $sloppy->analyze();

        $output->info(sprintf(
            'Findings %d -> %d. Score %d/100 -> %d/100.',
            $before->count(),
            $after->count(),
            $before->score->value,
            $after->score->value,
        ));
    }
}
